### PR TITLE
[#36,#38,#39] ELK: Fix elasticsearch, update to Ubuntu 24.04, switch to distro-provided JRE

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #36
Addresses #38
Addresses #39

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Using the `test1` tag of the image on your namespace of Dockerhub, which I assume is based off of these changes, I confirmed that I was able to stand up the stack and view the dashboard! Nice. # it

**Review by korydraughn — APPROVED** [review]

**Comment by alanking** [comment]
Although, I don't see any data coming through. But rumor has it that you're on the hunt for that, so... up to you if we wanna fix it piecemeal or just wait for the changes here.

**Comment by SwooshyCueb** [comment]
> Although, I don't see any data coming through. But rumor has it that you're on the hunt for that, so... up to you if we wanna fix it piecemeal or just wait for the changes here.

Yeah, just pushed up the fix for that. Python removed `_decompose` from `enum`, so `not-logstash` never actually ran.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
