### PR TITLE
[#41] ELK: Update for new rabbitmq and wrap not-logstash json decoding in exception handler

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #41 (probably)

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good. Did you confirm things are still working?

**Comment by SwooshyCueb** [comment]
Yup, everything is still working

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
